language: go

env:
  CODECOV_TOKEN="63cd9447-4f4f-4e38-8c74-aa66ff6a26d1"
before_install:
  - gem install sass

go:
  - 1.7
  - tip

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
