image: Visual Studio 2015

version: "{build}"
clone_folder: c:\go-work\src\gotable

environment:
  GOPATH: c:\go-work
  matrix:
    - RUBY_VERSION: "24"
    - RUBY_VERSION: "24-x64"

install:
  # use ruby 2.4, default one is 1.9.3, sass requires >=2.0, <2.5
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ruby --version
  - gem --version
  # make installation
  - cinst make -v -y
  # wkhtmltopdf installation
  - cinst wkhtmltopdf -v -y -d
  # sass installation
  - npm install -g sass
  - go get -u github.com/golang/lint/golint
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - echo %PATH%
  - go version
  - go env
  # build the dependency
  - make

build_script:
  - go build -o buildOutput\gotable -i .

artifacts:
  - path: buildOutput/gotable
    name: gotable

before_test:
  - make clean

test_script:
  - make test
  - make benchmark

on_success:
  - make clean
