image: Visual Studio 2015

version: "{build}"
clone_folder: c:\go-work\src\gotable

environment:
  GOPATH: c:\go-work

install:
  # use ruby 2.4, default one is 1.9.3, sass requires >=2.0, <2.5
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install
  # make installation
  - cinst make -v -y
  # wkhtmltopdf installation
  - cinst wkhtmltopdf -v -y -d
  # sass installation
  - gem install sass
  - go get -u github.com/golang/lint/golint
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - echo %PATH%
  - go version
  - go env
  # build the dependency
  - make

build_script:
  - go build -o buildOutput\gotable -i .

artifacts:
  - path: buildOutput/gotable
    name: gotable

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - make test
  - make benchmark

on_success:
  - make clean